/* 
 backgroundContent precisa ser no formato com 6 digitos ("#ffffff" não "#fff")
*/
const dark = {
  backgroundContainer: '#333',
  backgroundContent: '#555555',
  headerBackground: '#333',
  headerTitle: '#aaa',
  headerIndicator: "#aaa",
  weekDate: '#333',
  confirmDate: '#333',
  red: '#f00',
  green: "#0f0",
  orange: '#f90',
  gray: '#ccc',
  purple: '#a0f',
  blue: '#00f',
  white: '#fff',
  btnText: '#555',
  strong: "#ddd",
  text: '#aaa',
  weakText: "#888",
  statusBar: '#333',
  border: '#666',
  flag: '#eee',
  weakInverse: "#888",
  activeBackgroundColor: '#aaa',
  activeColor: '#333',
  drawerBackground: '#555',
  tooltipBackground: '#ccc',
  tooltipText: '#333',
  checkboxColor: '#aaa',
};

const light = {
  backgroundContainer: '#eee',
  backgroundContent: '#ffffff',
  headerBackground: '#070',
  headerTitle: '#fff',
  headerIndicator: "#0f0",
  weekDate: '#070',
  confirmDate: '#070',
  red: '#a00',
  green: 'green',
  orange: '#f70',
  gray: '#333',
  purple: '#80d',
  blue: '#00a',
  white: '#fff',
  btnText: '#eee',
  strong: "#333",
  text: '#888',
  weakText: '#aaa',
  statusBar: '#070',
  border: '#ccc',
  flag: '#fff',
  weakInverse: "#ddd",
  activeBackgroundColor: '#070',
  activeColor: '#fff',
  drawerBackground: '#fff',
  tooltipBackground: '#333',
  tooltipText: '#fff',
  checkboxColor: '#070',
};

export {dark, light};
