const dark = {
  backgroundContainer: '#333',
  backgroundContent: '#555',
  headerTitle: '#aaa',
  red: '#f00',
  green: "#0f0",
  orange: '#f90',
  gray: '#ccc',
  purple: '#a0f',
  blue: '#00f',
  white: '#fff',
  btnText: '#555',
  text: '#aaa',
  weakText: "#888",
  statusBar: '#f00',
  border: '#666',
  flag: '#eee',
  weakInverse: "#888",
  activeBackgroundColor: '#aaa',
  activeColor: '#333',
  drawerBackground: '#555',
};

const light = {
  backgroundContainer: '#eee',
  backgroundContent: '#fff',
  headerTitle: '#333',
  red: '#a00',
  green: 'green',
  orange: '#f70',
  gray: '#333',
  purple: '#80d',
  blue: '#00a',
  white: '#fff',
  btnText: '#eee',
  text: '#888',
  weakText: '#aaa',
  statusbar: '#0f0',
  border: '#ccc',
  flag: '#fff',
  weakInverse: "#ddd",
  activeBackgroundColor: '#070',
  activeColor: '#fff',
  drawerBackground: '#fff',
};

export {dark, light};
